### PR TITLE
Allow user to change the price of a fixed price sale

### LINKED ISSUE #513: Update fixed price sale
Allow user to change the price of a fixed price sale

### PR DESCRIPTION
**Pull request by aidan-starke**
## Description

- closes #513

#### Adds

- fn `update_fixed_price()` in lib.rs and weights.rs
- new Event `FixedPriceSalePriceUpdated`
- tests

### CODE REVIEW

File: crml/nft/src/lib.rs [hunk 1]
```diff
@@ -191,6 +193,8 @@ decl_storage! {
 		pub NextListingId get(fn next_listing_id): ListingId;
 		/// NFT sale/auction listings keyed by collection id and token id
 		pub Listings get(fn listings): map hasher(twox_64_concat) ListingId => Option<Listing<T>>;
+		/// Current price on fixed price listing
+		pub ListingCurrentFixedPrice get(fn current_price): map hasher(twox_64_concat) ListingId => Balance;
```
Comment (JasonTulp) [inline crml/nft/src/lib.rs]: This storage map isn't being used

File: crml/nft/src/lib.rs [hunk 2]
```diff
@@ -853,6 +857,35 @@ decl_module! {
...
+			let origin = ensure_signed(origin)?;
+
+			match Self::listings(listing_id) {
+				Some(Listing::<T>::FixedPrice(mut sale)) => {
+					ensure!(sale.seller == origin, Error::<T>::NoPermission);
+
+					sale.fixed_price = new_price;
+					let collection_id = sale.tokens[0].0;
+
+					Listings::mutate(listing_id, |listing| *listing = Some(Listing::<T>::FixedPrice(sale)));
```
Comment (JasonTulp) [inline crml/nft/src/lib.rs]: I believe you can just use an insert here
```suggestion
					Listings::insert(listing_id, Some(Listing::<T>::FixedPrice(sale)));
```

**Review by JasonTulp — COMMENTED** [review]
Looks good man :) Nicely done

File: crml/nft/src/lib.rs (hunk 2 above)
Comment (jordy25519) [reply crml/nft/src/lib.rs]: yes `Listings::insert(listing_id, sale);` is better here since the value `(sale)` is already loaded.
`mutate` will try read the value from storage again and decode for no reason since it gets overwritten

**Review by jordy25519 — APPROVED** [review]
lgtm! - the mutate
